plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
}

group = "io.github.nguyenduck"
version = "1.1.0"

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()

    implementation "com.github.javaparser:javaparser-core:3.25.8"

    compileOnly "com.android.tools.build:gradle:8.0.0"
}

gradlePlugin {
    plugins {
        autoAidl {
            id = "io.github.nguyenduck.autoaidl"
            implementationClass = "io.github.nguyenduck.autoaidl.AutoAIDLPlugin"
        }
    }
}

publishing {
    repositories {
        maven {
            name = "GithubPackages"
            url = uri("https://maven.pkg.github.com/NguyenDuck/AutoAIDL")
            credentials {
                username = project.findProperty("gpr.user")
                password = project.findProperty("gpr.key")
            }
        }
    }
}