plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
}

repositories {
    google()
    mavenCentral()
}

publishing {
    repositories {
        maven {
            name = "GithubPackages"
            url = uri("https://maven.pkg.github.com/NguyenDuck/AutoAIDL")
            credentials {
                username = project.findProperty("gpr.user")
                password = project.findProperty("gpr.key")
            }
        }
    }
}