plugins {
    id 'com.android.application'
    id 'io.github.nguyenduck.autoaidl' version '1.1.9'
}

repositories {
    google()
    mavenCentral()
    mavenLocal()
}

group = 'com.example'
version = '1.0.0'

android {
    namespace 'com.example'
    compileSdk 36

    defaultConfig {
        applicationId "com.example"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        aidl true
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'

    implementation "dev.rikka.shizuku:api:13.1.5"
    implementation "dev.rikka.shizuku:provider:13.1.5"
}